name: Build
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mvn ${MAVEN_CLI_OPTS} package -DskipTests
    - name: Test with Maven
      run: |
        mvn ${MAVEN_CLI_OPTS} test
        mvn ${MAVEN_CLI_OPTS} install -DskipTests
        mvn ${MAVEN_CLI_OPTS} failsafe:integration-test failsafe:verify
    
    env:
      MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
